# Generated by Django 5.0.1 on 2024-02-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_worldgeopark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worldgeopark',
        ),
    ]
